# Generated by Django 4.1.7 on 2023-02-26 16:32

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='code',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, unique=True, verbose_name='코드'),
        ),
    ]
