# Generated by Django 4.1.7 on 2023-02-26 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='이름'),
        ),
    ]
